### ISSUE TITLE
Clean up README.md file

### ISSUE THREAD

**Issue by jenlampton** [backdrop-contrib/date_tools#6]
The README.md file for this project is not properly formatted.  Sometimes this can happen when projects are ported over from Drupal, since there wasn't a lot of direction on formatting of Drupal's README.txt files.  Please refer to our [contributor guidelines](https://github.com/backdrop-ops/contrib) for an [example README.md file](https://raw.githubusercontent.com/backdrop-ops/contrib/master/examples/README.md) that you can copy. 

The main problem is the HTML formatting which needs to be removed. Markdown files (ending in .md) have [their own formatting](https://help.github.com/articles/markdown-basics) similar to what we use here on GitHub :)

It is especially important to keep the readme files clean for Backdrop projects since that is what is used for the project page on backdropcms.org.  Take a look at the page for this project to see the problem: https://backdropcms.org/project/date-tools

**Comment by Graham-72** [comment]
Attempted to put this right with commit https://github.com/backdrop-contrib/date_tools/commit/a41ccdf

**Comment by Graham-72** [comment]
@jenlampton What am I doing wrong? I have removed the HTML formatting but it is being added back somewhere:
![modules for backdrop cms - backdrop cms 2015-09-23 06-23-09](https://cloud.githubusercontent.com/assets/10559274/10038305/0bf9e894-61bc-11e5-8add-79c91f84e6aa.png)

**Comment by jenlampton** [comment]
It's not you, it's me. Something changed on backdropcms.org recently that was causing all the HTML formatting to appear.  I believe we've fixed it now, sorry about the trouble (and for the false issue).  Thank  you for contributing this module for Backdrop :)
